Module:
  Receiver:
    download_manager_class: DownloadManagerImplementation
    download_manager_module: DownloadManager
    start_server_class: DefaultStartServerImplementation
    start_server_module: DefaultStartServer
  Sender:
    discover_receiver_class: DefaultDiscoveringImplementation
    discover_receiver_module: DefaultDiscoveringImplementation
    sending_file_class: DefaultSendingFileImplementation
    sending_file_module: DefaultSendingFileImplementation
#    user_interface_class: GUIHandler
#    user_interface_module: TkinterGUI
    user_interface_class: QtUIHandler
    user_interface_module: QtGUI

Settings:
  Receiver:
    name: erfan
    path: null
    receive_port: 5000
    receiver_host: 0.0.0.0
  Sender:
    discovery_port: 5000
    discovery_timeout: 1.0
    send_port: 25622
